### PR TITLE
Makes the role more reusable and adds a test script runner

### PR DESCRIPTION
**Pull request by MassiveHiggsField**
I removed the requirement to set something like this before the role is executed:

    - name: installing repo for Java 8 in Ubuntu
      apt_repository: repo='ppa:openjdk-r/ppa'

This way the role detects what is needed and adds the repositories accordingly.  Additionally i added a test runner and added tests for every supported combination of jdk and distro. 

The only distro not to support jdk 7 and 8 is fedora, so no test has been added for that setup.

### CODE REVIEW

**Comment by MassiveHiggsField** [comment]
Intention here was to make it easier to depend on this role in other galaxy roles.

**Comment by geerlingguy** [comment]
@MassiveHiggsField - This is a huge architectural change to the role, and I'd rather keep it (especially the testing portions) aligned with all my other roles to keep down maintenance. I tend to favor not adding extra test scaffolding, because with the way it currently is, you can run a few docker commands to run all tests locally, so I'd like to keep it that way.

Also, regarding the versions, PPA's, etc., I favor targeting the latest LTS release, but allowing people to customize for older releases (both for CentOS and Debian/Ubuntu), therefore I'd like to keep all the specific repo setups in the test files and not make it part of the role itself, as that makes debugging installation problems a lot harder, especially for people who need to use the role with the LTS release's built-in packages.

**Comment by MassiveHiggsField** [comment]
The test runner is completely based on your test architecture, it's just a more convenient way to start them locally (its just a shell wrapper around the docker commands).

Regarding the PPAs etc, is it just that you don't want to support them? The changes in the PR make everything totally optional and is only added if someone explicitly selects a combination which needs additional repos. 

The problem for me here is, if i develop a role which is dependent on this role and i want to support such a combination, i don't think i have any way to automatically add the needed repos. If for instance i have this in my metas:

     dependencies:
       - src: geerlingguy.ansible-role-java
         java_packages:
           - 'openjdk-8-jdk'

Now if anyone wants to use my role in his playbook and wants to use a non-supported combination, i cannot add the repository before the dependency is executed. The only way to do this, as i see it, is to use another dependency on a role which can add repositories or to add a warning to the readme. Or do you see another way to do this?

**Comment by geerlingguy** [comment]
I generally tell people to configure the versions for things like Java, Git, etc. in their playbooks/vars, and assume that each role could be run independently, rather than adding hard dependencies on other roles with specific version combinations... but I see you point.

When you define dependencies in that way, in meta.yml, does it actually force the `java_packages` when using the role in a playbook? I didn't think the meta dependency information was used at all during playbook runs, only for Galaxy information.

**Comment by MassiveHiggsField** [comment]
Actually my meta yaml looks like this at the moment (i know, i know... :) ):

    dependencies:
      - src: https://github.com/MassiveHiggsField/ansible-role-java/archive/master.tar.gz
        name: MassiveHiggsField.ansible-role-java
        java_packages:
          - 'java-1.7.0-openjdk'
        when:
          - selenium_server_version[0:1] == '2'
          - ansible_os_family == 'RedHat'
    
      - src: https://github.com/MassiveHiggsField/ansible-role-java/archive/master.tar.gz
        name: MassiveHiggsField.ansible-role-java
        java_packages:
          - 'java-1.8.0-openjdk'
        when:
          - selenium_server_version[0:1] == '3'
          - ansible_os_family == 'RedHat'
    
      - src: https://github.com/MassiveHiggsField/ansible-role-java/archive/master.tar.gz
        name: MassiveHiggsField.ansible-role-java
        java_packages:
          - 'openjdk-7-jdk'
        when:
          - selenium_server_version[0:1] == '2'
          - ansible_os_family == 'Debian'
    
      - src: https://github.com/MassiveHiggsField/ansible-role-java/archive/master.tar.gz
        name: MassiveHiggsField.ansible-role-java
        java_packages:
          - 'openjdk-8-jdk'
        when:
          - selenium_server_version[0:1] == '3'
          - ansible_os_family == 'Debian'

And that works pretty good. Of course its not the prettiest :) 

But you're probably right, keeping "soft" dependencies is a better way.

**Comment by lhoss** [comment]
Like @MassiveHiggsField I would *really* like not to have to care about adding a ppa 'pre_task'  in any playbook requiring java 8 (on our still mostly used Ubuntu 14.04) servers.
I actually like following approach the most, taken from one of the forks, and applied to latest master:
https://github.com/lhoss/ansible-role-java/pull/1/files

Could that have a chance to goto master @geerlingguy ?
OR with adding  an extra flag like `java_debian_ppa_repos_enabled` (false by default)?

**Pull request closed without merging**
